@echo off
setlocal enabledelayedexpansion

REM Auto-generated by init_build.bat - Selective build
set "DIR=%~dp0"
set "DIR=!DIR:~0,-1!"
set "KFLIB=%~dp0..\base\KF.lib"
set "CXXFLAGS=/O2 /std:c++17 /utf-8 /EHsc /MD /I%~dp0..\"
set "LINKFLAGS=/OPT:REF /OPT:ICF /SUBSYSTEM:CONSOLE"

REM Setup MSVC environment if not already set
if not defined INCLUDE call "%~dp0..\init_build.bat" --setup

set "filecount=0"
for %%f in ("!DIR!\*.cpp") do (
    set /a filecount+=1
    set "file_!filecount!=%%~nxf"
    set "filepath_!filecount!=%%f"
)

if "!filecount!"=="0" (
    echo No .cpp files found.
    pause
    exit /b 0
)

echo +----------------------------------------+
echo   KForge Build  -  
echo +----------------------------------------+
echo.
echo   Files in this directory:
for /l %%i in (1,1,!filecount!) do echo     %%i. !file_%%i!
echo.
set "choice="
set /p "choice=  Select numbers (e.g. 1,3) or Enter for all: "

if not exist "!DIR!\Release" mkdir "!DIR!\Release"

set "compileall=1"
if defined choice (
    set "sel=!choice:,= !"
    set "seltrimmed=!sel: =!"
    if not "!seltrimmed!"=="" set "compileall=0"
)

if "!compileall!"=="1" (
    for /l %%i in (1,1,!filecount!) do (
        call :compile_one "!filepath_%%i!" "!file_%%i:~0,-4!"
        if errorlevel 1 goto :build_err
    )
) else (
    for %%n in (!sel!) do (
        if defined filepath_%%n (
            call :compile_one "!filepath_%%n!" "!file_%%n:~0,-4!"
            if errorlevel 1 goto :build_err
        ) else (
            echo   [WARN] Invalid: %%n
        )
    )
)

echo.
echo   [DONE] Build complete. Output: !DIR!\Release\
pause
goto :build_end

:compile_one
set "cf=%~1"
set "cn=%~2"
echo   [BUILD] !cn!.cpp
cl /c !CXXFLAGS! "!cf!" /Fo:"!DIR!\Release\!cn!.obj"
if errorlevel 1 (
    echo   [FAIL] !cn!.cpp - compile error
    exit /b 1
)
link !LINKFLAGS! "!KFLIB!" "!DIR!\Release\!cn!.obj" /out:"!DIR!\Release\!cn!.exe"
if errorlevel 1 (
    echo   [FAIL] !cn!.cpp - link error
    exit /b 1
)
del "!DIR!\Release\!cn!.obj"
echo   [OK] !cn!.cpp
exit /b 0

:build_err
echo   [ERROR] Build failed.
pause
exit /b 1

:build_end
endlocal
exit /b 0
