@echo off
setlocal enabledelayedexpansion

REM Auto-generated by init_build.bat - Fast build all
set "DIR=D:\kForge\test"
set "KFLIB=D:\kForge\base\KF.lib"
set "CXXFLAGS=/O2 /std:c++17 /utf-8 /EHsc /MD /ID:\kForge"
set "LINKFLAGS=/OPT:REF /OPT:ICF /SUBSYSTEM:CONSOLE"

REM Setup MSVC environment if not already set
if not defined INCLUDE call "D:\kForge\init_build.bat" --setup

set "filecount=0"
for %%f in ("!DIR!\*.cpp") do (
    set /a filecount+=1
    set "file_!filecount!=%%~nxf"
    set "filepath_!filecount!=%%f"
)

if "!filecount!"=="0" (
    echo No .cpp files found.
    pause
    exit /b 0
)

echo +----------------------------------------+
echo   KForge Fast Build  -  test
echo +----------------------------------------+
echo.
if exist "!DIR!\Release" rd /s /q "!DIR!\Release"
mkdir "!DIR!\Release"

for /l %%i in (1,1,!filecount!) do (
    set "cf=!filepath_%%i!"
    set "cn=!file_%%i:~0,-4!"
    echo   [BUILD] !cn!.cpp
    cl /c !CXXFLAGS! "!cf!" /Fo:"!DIR!\Release\!cn!.obj"
    if errorlevel 1 (
        echo   [FAIL] !cn!.cpp
        pause
        exit /b 1
    )
    link !LINKFLAGS! "!KFLIB!" "!DIR!\Release\!cn!.obj" /out:"!DIR!\Release\!cn!.exe"
    if errorlevel 1 (
        echo   [FAIL] !cn!.cpp - link error
        pause
        exit /b 1
    )
    del "!DIR!\Release\!cn!.obj"
    echo   [OK] !cn!.cpp
)

echo.
echo   [DONE] All built. Output: !DIR!\Release\
pause
endlocal
exit /b 0
